camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

bpmn:
  flows:
    party-lookup: "PayeePartyLookup-{tenant}"
    quote: "PayeeQuoteTransfer-{tenant}"
    transaction-request: "PayerTransactionRequest-{tenant}"

zeebe:
  client:
    max-execution-threads: 1000
    evenly-allocated-max-jobs: 1000
#    max-execution-threads: 100
#    number-of-workers: 15
#    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "ph-ee-zeebe:26500"

connector:
  ilp-secret: h4on38bsDjKiat2783gnklgafikmeuu5123kpobb7jm99

mojaloop:
  enabled: true
  perf-mode: false
  perf-resp-delay: 100

switch:
  quotes-host: http://40.114.81.46
  quote-service: quoting-service.local
  als-host: http://40.114.81.46
  account-lookup-service: account-lookup-service.local
  transfers-host: http://40.114.81.46
  transfer-service: ml-api-adapter.local
  transactions-host: http://40.114.81.46
  transaction-request-service: transaction-request-service.local
  oracle-host: http://account-oracle.mifos.io:4100

dfspids: "DFSPID"

logging:
  level:
    root: ERROR
